In [1]:
# Libaries
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt

import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# Read the data and create df
numerical = pd.read_csv(r"C:\Users\ljant\Downloads\numerical.csv")
targets = pd.read_csv(r"C:\Users\ljant\Downloads\target.csv")
categorical = pd.read_csv(r"C:\Users\ljant\Downloads\categorical.csv")

df = pd.concat([numerical, categorical, targets], axis = 1)
df

,TCODE,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,...,MINRDATE_YR,MINRDATE_MM,MAXRDATE_YR,MAXRDATE_MM,LASTDATE_YR,LASTDATE_MM,FIRSTDATE_YR,FIRSTDATE_MM,TARGET_B,TARGET_D
0,0,60.000000,5,9,0,0,39,34,18,10,...,92,8,94,2,95,12,89,11.0,0,0.0
1,1,46.000000,6,9,16,0,15,55,11,6,...,93,10,95,12,95,12,93,10.0,0,0.0
2,1,61.611649,3,1,2,0,20,29,33,6,...,91,11,92,7,95,12,90,1.0,0,0.0
3,0,70.000000,1,4,2,0,23,14,31,3,...,87,11,94,11,95,12,87,2.0,0,0.0
4,0,78.000000,3,2,60,1,28,9,53,26,...,93,10,96,1,96,1,79,3.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1,61.611649,5,9,0,14,36,47,11,7,...,96,2,96,2,96,2,96,2.0,0,0.0
95408,1,48.000000,7,9,1,0,31,43,19,4,...,96,3,96,3,96,3,96,3.0,0,0.0
95409,1,60.000000,5,9,0,0,18,46,20,7,...,96,3,95,1,96,10,94,10.0,0,0.0
95410,0,58.000000,7,9,0,0,28,35,20,9,...,90,11,96,8,97,1,86,12.0,1,18.0
95411,2,80.000000,5,8,3,1,33,22,27,8,...,88,12,93,12,96,12,88,3.0,0,0.0

In [3]:
def header_function (data):
    cols = []
    for i in range (len(data.columns)):
        cols.append(data.columns[i].lower().replace(' ','_'))
    
    data.columns = cols

    return data

header_function(df)

,tcode,age,income,wealth1,hit,malemili,malevet,vietvets,wwiivets,localgov,...,minrdate_yr,minrdate_mm,maxrdate_yr,maxrdate_mm,lastdate_yr,lastdate_mm,firstdate_yr,firstdate_mm,target_b,target_d
0,0,60.000000,5,9,0,0,39,34,18,10,...,92,8,94,2,95,12,89,11.0,0,0.0
1,1,46.000000,6,9,16,0,15,55,11,6,...,93,10,95,12,95,12,93,10.0,0,0.0
2,1,61.611649,3,1,2,0,20,29,33,6,...,91,11,92,7,95,12,90,1.0,0,0.0
3,0,70.000000,1,4,2,0,23,14,31,3,...,87,11,94,11,95,12,87,2.0,0,0.0
4,0,78.000000,3,2,60,1,28,9,53,26,...,93,10,96,1,96,1,79,3.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1,61.611649,5,9,0,14,36,47,11,7,...,96,2,96,2,96,2,96,2.0,0,0.0
95408,1,48.000000,7,9,1,0,31,43,19,4,...,96,3,96,3,96,3,96,3.0,0,0.0
95409,1,60.000000,5,9,0,0,18,46,20,7,...,96,3,95,1,96,10,94,10.0,0,0.0
95410,0,58.000000,7,9,0,0,28,35,20,9,...,90,11,96,8,97,1,86,12.0,1,18.0
95411,2,80.000000,5,8,3,1,33,22,27,8,...,88,12,93,12,96,12,88,3.0,0,0.0

In [4]:
df.drop_duplicates()

,tcode,age,income,wealth1,hit,malemili,malevet,vietvets,wwiivets,localgov,...,minrdate_yr,minrdate_mm,maxrdate_yr,maxrdate_mm,lastdate_yr,lastdate_mm,firstdate_yr,firstdate_mm,target_b,target_d
0,0,60.000000,5,9,0,0,39,34,18,10,...,92,8,94,2,95,12,89,11.0,0,0.0
1,1,46.000000,6,9,16,0,15,55,11,6,...,93,10,95,12,95,12,93,10.0,0,0.0
2,1,61.611649,3,1,2,0,20,29,33,6,...,91,11,92,7,95,12,90,1.0,0,0.0
3,0,70.000000,1,4,2,0,23,14,31,3,...,87,11,94,11,95,12,87,2.0,0,0.0
4,0,78.000000,3,2,60,1,28,9,53,26,...,93,10,96,1,96,1,79,3.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1,61.611649,5,9,0,14,36,47,11,7,...,96,2,96,2,96,2,96,2.0,0,0.0
95408,1,48.000000,7,9,1,0,31,43,19,4,...,96,3,96,3,96,3,96,3.0,0,0.0
95409,1,60.000000,5,9,0,0,18,46,20,7,...,96,3,95,1,96,10,94,10.0,0,0.0
95410,0,58.000000,7,9,0,0,28,35,20,9,...,90,11,96,8,97,1,86,12.0,1,18.0
95411,2,80.000000,5,8,3,1,33,22,27,8,...,88,12,93,12,96,12,88,3.0,0,0.0

In [5]:
sum_na = df.isna().sum()
print (sum_na)

nan_columns = sum_na[sum_na != 0]
print('Columns with NaN values:\n', nan_columns)

df = df.dropna()

tcode           0
age             0
income          0
wealth1         0
hit             0
               ..
lastdate_mm     0
firstdate_yr    0
firstdate_mm    2
target_b        0
target_d        0
Length: 339, dtype: int64
Columns with NaN values:
 firstdate_mm    2
dtype: int64

In [6]:
# Cleaning data for model

X = df.drop(['target_b', 'target_d'], axis = 1)
Y_b = df['target_b']
Y_d = df['target_d']

numericalX = X.select_dtypes('number').reset_index(drop = True)
categorcalX = X.select_dtypes('object').reset_index(drop = True)
categorcalX = categorcalX.drop(['state'], axis = 1)
categorcalX = pd.get_dummies(categorcalX[['homeownr', 'gender', 'rfa_2r', 'rfa_2a', 'geocode2', 'domain_a']], dtype = int)

X = pd.concat([numericalX, categorcalX], axis = 1)

# Train-Test-Split

In [7]:
X_train, X_test, Y_train_b, Y_test_b, Y_train_d, Y_test_d = train_test_split(X, Y_b,Y_d, test_size=0.2, random_state=0)
train = pd.concat([X_train.reset_index(drop=True), 
                   Y_train_b.reset_index(drop=True), 
                   Y_train_d.reset_index(drop=True)], axis=1)

# Optimising Model

In [8]:
X_train.reset_index(drop=True, inplace=True)
Y_train_b.reset_index(drop=True, inplace=True)

def significant_features(X, Y):
    """
    Select independent variables with P>|z| < 0.05 from the Logit model summary.
    """
    model = sm.Logit(Y_train_b, X_train).fit()
    summary = model.summary()

    significant_features = []
    table = summary.tables[1]
    headers = table.data[0]
    data = table.data[1:]

    p_value_index = headers.index('P>|z|') if 'P>|z|' in headers else headers.index('P>|z| [0.025')

    for row in data:
        p_value = float(row[p_value_index])
        if p_value < 0.05:
            significant_features.append(row[0])

    return significant_features

relevant_features = significant_features(X_train, Y_train_b)
print("Independent variables with P>|t| < 0.05:", relevant_features)

Optimization terminated successfully.
         Current function value: 0.191885
         Iterations 9
Independent variables with P>|t| < 0.05: ['age', 'income', 'age907', 'hhn3', 'hu1', 'hu3', 'hu4', 'ethc2', 'rhp1', 'rhp2', 'dma', 'ic11', 'tpe7', 'lfc2', 'lfc4', 'occ6', 'ec1', 'sec1', 'anc10', 'anc14', 'voc3', 'cardprom', 'numprom', 'ngiftall', 'cardgift', 'rfa_2f', 'odatew_mm', 'dob_mm', 'minrdate_yr', 'lastdate_yr', 'lastdate_mm', 'firstdate_yr']

In [9]:
X_train_adj = X_train[relevant_features]
X_test_adj = X_test[relevant_features]

model = LogisticRegression()
model.fit(X_train_adj, Y_train_b)

print(model.score(X_train_adj, Y_train_b))
print(model.score(X_test_adj, Y_test_b))

0.9497956189078713
0.9470181322712504

# Dealing with Unbalance

In [10]:
train = pd.concat([X_train_adj.reset_index(drop=True), 
                   Y_train_b.reset_index(drop=True), 
                   Y_train_d.reset_index(drop=True)], axis=1)
print(train['target_b'].value_counts())

0    72496
1     3832
Name: target_b, dtype: int64

In [11]:
from sklearn.utils import resample
assert not train['target_d'].isnull().any(), "NaNs in original target_d"
category_0 = train[train['target_b'] == 0]
category_1 = train[train['target_b'] == 1]

# Undersample majority
category_0_undersampled = resample(category_0,
                                   replace=False, 
                                   n_samples=len(category_1),
                                   random_state=0)

# Combine undersampled and minority category
train_undersampled = pd.concat([category_0_undersampled, category_1], axis=0)

# Check for NaNs after concatenation
assert not train_undersampled['target_d'].isnull().any(), "NaNs introduced during resampling"

# Separating the features and target variables
Y_train_undersampled_b = train_undersampled['target_b']
Y_train_undersampled_d = train_undersampled['target_d']
X_train_undersampled = train_undersampled.drop(['target_b', 'target_d'], axis=1)

print(train_undersampled['target_b'].value_counts())

0    3832
1    3832
Name: target_b, dtype: int64

In [12]:
model = LogisticRegression()
model.fit(X_train_undersampled, Y_train_undersampled_b)

print(model.score(X_train_undersampled, Y_train_undersampled_b))
print(model.score(X_test_adj, Y_test_b))

0.5700678496868476
0.5840058694057226

# Predicting 'target_d'

In [13]:
# 1. Make predictions on the train set
predictions_target_b_train = model.predict(X_train_undersampled)

In [14]:
# 2. Filter the data for donors
X_train_d = X_train_undersampled[predictions_target_b_train == 1]
Y_train_d = Y_train_undersampled_d[predictions_target_b_train == 1]

In [15]:
# 3. Train Regression Model for 'target_d' (linear regression)
model_d = sm.OLS(Y_train_d, X_train_d).fit()
model_d.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:               target_d   R-squared (uncentered):                   0.372
Model:                            OLS   Adj. R-squared (uncentered):              0.366
Method:                 Least Squares   F-statistic:                              68.36
Date:                Thu, 25 Jan 2024   Prob (F-statistic):                        0.00
Time:                        18:47:13   Log-Likelihood:                         -14162.
No. Observations:                3727   AIC:                                  2.839e+04
Df Residuals:                    3695   BIC:                                  2.859e+04
Df Model:                          32
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
age             -0.0049      0.014     -0.358      0.720      -0.032       0.022
income           0.4087      0.122      3.346      0.001       0.169       0.648
age907          -0.0671      0.061     -1.099      0.272      -0.187       0.053
hhn3            -0.0178      0.035     -0.516      0.606      -0.086       0.050
hu1              0.0119      0.016      0.728      0.467      -0.020       0.044
hu3             -0.0357      0.052     -0.683      0.495      -0.138       0.067
hu4             -0.0324      0.054     -0.599      0.549      -0.138       0.074
ethc2            0.0229      0.023      0.979      0.327      -0.023       0.069
rhp1             0.0854      0.073      1.177      0.239      -0.057       0.228
rhp2            -0.0614      0.087     -0.704      0.481      -0.232       0.109
dma              0.0043      0.002      2.169      0.030       0.000       0.008
ic11             0.0179      0.045      0.400      0.689      -0.070       0.106
tpe7            -0.2265      0.246     -0.919      0.358      -0.709       0.256
lfc2             0.0173      0.060      0.286      0.775      -0.101       0.136
lfc4             0.0074      0.056      0.131      0.896      -0.103       0.118
occ6             0.5561      0.160      3.478      0.001       0.243       0.870
ec1              0.0379      0.022      1.715      0.086      -0.005       0.081
sec1            -0.1781      0.082     -2.183      0.029      -0.338      -0.018
anc10            0.0751      0.057      1.317      0.188      -0.037       0.187
anc14           -0.2855      0.152     -1.882      0.060      -0.583       0.012
voc3            -0.0284      0.028     -1.028      0.304      -0.083       0.026
cardprom        -0.1896      0.074     -2.561      0.010      -0.335      -0.044
numprom          0.0992      0.023      4.282      0.000       0.054       0.145
ngiftall        -0.0321      0.048     -0.671      0.502      -0.126       0.062
cardgift        -0.0110      0.091     -0.121      0.904      -0.190       0.168
rfa_2f          -0.8656      0.179     -4.844      0.000      -1.216      -0.515
odatew_mm       -0.2768      0.696     -0.397      0.691      -1.642       1.089
dob_mm           0.1608      0.055      2.906      0.004       0.052       0.269
minrdate_yr     -0.0833      0.090     -0.930      0.352      -0.259       0.092
lastdate_yr     -0.1227      0.138     -0.889      0.374      -0.393       0.148
lastdate_mm     -0.0368      0.045     -0.814      0.416      -0.125       0.052
firstdate_yr     0.2279      0.130      1.752      0.080      -0.027       0.483
==============================================================================
Omnibus:                     3444.765   Durbin-Watson:                   1.195
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           313332.673
Skew:                           4.083   Prob(JB):                         0.00
Kurtosis:                      47.170   Cond. No.                     2.99e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.99e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
# 1. Make predictions on the test set
predictions_target_b_test = model.predict(X_test_adj)

# 2. Filter the data for donors
X_test_d = X_test_adj[predictions_target_b_test == 1]
Y_test_d = Y_test_d[predictions_target_b_test == 1]

In [17]:
predictions_target_d = model_d.predict(X_test_d)

In [18]:
mse = mean_squared_error(Y_test_d, predictions_target_d)
mae = mean_absolute_error(Y_test_d, predictions_target_d)
print("R2 value is = ",round(r2_score(Y_test_d, predictions_target_d),2))
print("The mse of the model is = ", round(mse,2))
print("The root mse of the model is = ",round(np.sqrt(mse),2))
print("The mean absolute error of the model is = ",round(mae,2))

R2 value is =  -2.46
The mse of the model is =  80.25
The root mse of the model is =  8.96
The mean absolute error of the model is =  8.06

In [23]:
sum_all = sum(predictions_target_d)
print('The expected sum of the donations are', round(sum_all, 2))

The expected sum of the donations are 64729.27